Add Top Info Block
oc-shopaholic/oc-tailwind-shopaholic-theme pull request #90
Opened 2021-03-03 04:35 UTC by GabixStudio

2021-03-29 06:23 UTC, kharanenka commented on config/fields.yaml
> +            type: richeditor
@lautsevich 
Ввиду новой версии нужно будет проверить концепцию выноса таких полей не в настройки темы, а в контентные файлы

2021-03-29 06:23 UTC, kharanenka commented on assets/src/js/app.js
> +import '/partials/content/top-info-block/top-info-block';
Обязательно нужно сделать code splitting для страниц, для получения большого pagespeed.
Если это общий блок для всех страниц, то будем считать этот файл js как общий для всех страниц

2021-03-29 06:23 UTC, kharanenka commented on partials/content/top-info-block/top-info-block.htm
> +            <svg class="w-5 h-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
SVG лучше вынести в файл, чтобы сократить общий html код

2021-03-29 06:23 UTC, kharanenka commented on partials/content/top-info-block/top-info-block.js
> +const adCloser = $('.js-adCloser');
1. JS нужно организовывать как классы.

2021-03-29 06:23 UTC, kharanenka commented on partials/content/top-info-block/top-info-block.js
> +const adWrapper = $('.js-adWrapper');
Именовать css классы на которые вешаются js события лучше именовать с префиксом "**_**" вместо "**js-**".
Например: _top-info-block-closer, _top-info-block-wrapper, _top-info-block-content

2021-03-29 06:23 UTC, kharanenka commented on partials/content/top-info-block/top-info-block.js
> +  adCloser.on('click', function () {
Для оптимизации будет неплохо получать partial ajax запросом и при необходимости вставлять html и показывать его.

2021-03-29 06:23 UTC, kharanenka commented on partials/content/top-info-block/top-info-block.js
> +  if (localStorage.getItem('adContent') != adContent){
Обязательно необходимо разбить эту логику на функции класса и написать аннотации для каждой функции с комментарием о том, что делает функция

2021-03-29 19:03 UTC, lautsevich commented on config/fields.yaml
> +            type: richeditor
Нет, это не совсем подходит. Я вообще пока не вижу настроек с разграничением прав на редактирование отдельных узлов дерева файлов в Editor. Скорее всего для безопасности в такой раздел все еще не стоит лазить "домохозяйкам".

В т.ч. лучше держать в настройках темы, чтобы все более-менее в одном месте было, а не размазано по всей админке.

2021-03-29 19:04 UTC, lautsevich commented on assets/src/js/app.js
> +import '/partials/content/top-info-block/top-info-block';
Мы code splitting отложили на потом. Сейчас пока просто собираем js в единый бандл, а потом все распилим. Так мы и выигрыш в производительности четко замеряем и не переусложняем сболрку и настройку webpack сейчас.

2021-03-29 19:07 UTC, lautsevich commented on partials/content/top-info-block/top-info-block.htm
> +            <svg class="w-5 h-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
В этот SVG нужно прокидывать CSS, это возможно только, когда SVG является частью DOM. Единственное, @GabixStudio, нашёл необычный способ через вендорное свойство с префиксом `-webkit`, тогда не нужно держать в DOM. Но это прямо магия какая-то, я впервые про такое свойство слышу и пока не очень догоняю, насколько его безопасно юзать. Так что пока просто оставим стандартный рабочий способ.

2021-03-29 19:10 UTC, GabixStudio commented on partials/content/top-info-block/top-info-block.htm
> +            <svg class="w-5 h-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
Вообще, насколько помню, именно в этом месте не нужно взаимодействие с svg, поэтому можно подумать о выносе в файл.

2021-03-29 19:17 UTC, lautsevich commented on partials/content/top-info-block/top-info-block.htm
> +            <svg class="w-5 h-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
Думаю, все же при наведении нужно слегка менять цвет крестика. Завтра обсудим вместе с @Mary-Plashchynskaya.

2021-03-30 04:42 UTC, lautsevich commented on partials/content/top-info-block/top-info-block.js
> +  adCloser.on('click', function () {
Здесь есть риск нарушения метрики [CLS](https://web.dev/cls/) (Lighthouse). В целом я за то, что бы в DOM не было того, что не нужно юзеру, но метрики нарушать не можем, тем более, что с мая 2021 они станут серьёзным фактором ранжирования.

@wobqqq, ты это сделай, но оставь тудушку:
```
TODO: Check Lighthouse CLS later.
```

2021-04-01 08:13 UTC, lautsevich requested changes
Да и в  целом фронт собирается, но падает сошибкой.

![Screenshot from 2021-04-01 11-12-46](https://user-images.githubusercontent.com/196445/113264068-359e6c00-92db-11eb-9c9d-e5a2741cf7be.png)

2021-04-01 08:13 UTC, lautsevich commented on layouts/main.htm
> +        {% partial 'content/top-info-block/top-info-block-wrapper' %}
В папке `partials` у нас теперь будет плоская структура без группировки.

Во-первых, Октябрь до сих пор не поддерживает вложенность в админке. Из-за чего нам нередко пишут вопросы на этот счет.

Во-вторых, новый Октябрь сразу сломался о такой структуры. Это поправили, но сказали, что Editor точно пока не будет поддерживать вложенность более одного уровня. А этот инструмент позиционируется, в т.ч. для разработки.

Так что вернемся к вопросу вложенности, когда Октябрь это будет поддерживать. Пока же все пути надо поправить.

2021-04-01 08:13 UTC, lautsevich commented on layouts/static.htm
> +        {% partial 'content/top-info-block/top-info-block-wrapper' %}
Он должен вызываться `<header>`.

2021-04-01 08:13 UTC, lautsevich commented on partials/content/top-info-block/top-info-block.js
> +  /**
Зачем в первой строке два `*` достаточно же одного.

2021-04-01 10:05 UTC, lautsevich approved these changes
Теперь ок с моей стороны.

2021-04-01 13:15 UTC, kharanenka commented on partials/scripts/scripts.htm
> +<script src="{{ path_manifest_js }}"></script>
Не вижу необходимости в данном partial

2021-04-01 13:16 UTC, kharanenka commented on partials/top-info-block/top-info-block-ajax.htm
> +        <svg class="w-5 h-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
SVG лучше грузить как файл, а не вставлять в код

2021-04-01 13:16 UTC, kharanenka commented on partials/top-info-block/top-info-block.htm
> +<div class="bg-gray-100 p-4 xl:py-2 hidden _top-info-block" data-hash="{{ sTopInfoBlockHash }}"></div>
Не вижу смысла в этом partial. Этот код лучше разместить в heaser.htm

2021-04-01 13:18 UTC, lautsevich commented on partials/scripts/scripts.htm
> +<script src="{{ path_manifest_js }}"></script>
Мы выносим сюда все подключаемые перед </body> скрипты.

2021-04-01 13:20 UTC, kharanenka commented on partials/scripts/scripts.htm
> +<script src="{{ path_manifest_js }}"></script>
Такое дробление избыточно. Я как-то рассказывал, что подключения partial грузит рендер шаблонов. И лучше избавляться от "пустых" partial в пару строк

2021-04-01 13:20 UTC, lautsevich commented on partials/top-info-block/top-info-block.htm
> +<div class="bg-gray-100 p-4 xl:py-2 hidden _top-info-block" data-hash="{{ sTopInfoBlockHash }}"></div>
Мы распиливаем интерфейс на компоненты.

2021-04-01 13:26 UTC, lautsevich commented on partials/scripts/scripts.htm
> +<script src="{{ path_manifest_js }}"></script>
Я ставлю целью сделать из этого фреймворк по примеру, например, [T4](https://www.joomlart.com/t4-framework). Так что это история про DX. И да, кнопка тоже будет partial. 

Будем мерять скорость, когда соберем все. Тогда и решения принимать будем, отталкиваясь от цифр. Мы с тобой еще обсуждали, что возможно, можно сделать сборку шаблонов по типу фронта. Когда все `partials` склеиваются.

2021-04-01 13:44 UTC, lautsevich commented on partials/top-info-block/top-info-block-ajax.htm
> +        <svg class="w-5 h-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
В этот SVG будет прокидываться из CSS цвет при ховере.

2021-04-05 18:34 UTC, merged